[project]
name = "aws-bedrock-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awscli>=1.40.7",
    "boto3>=1.38.8",
]
